### ISSUE TITLE
Network Error with Animesync Server on Cloud

### ISSUE THREAD

**Issue by Thiago-Heleno** [animeloyalty/animesync#29]
I tried to host the server on Heroku and it keeps sending this error, even though I'm not using any Proxy

"statusCode":500,"message":"page.goto: net::ERR_TUNNEL_CONNECTION_FAILED at https://www.funimation.com/shows/all-shows/?audio=japanese&sort=popularity&p=1

[url]
https://server-skyline.herokuapp.com/api/remote/page?provider=funimation&page=popularity&&pageNumber=1

**Comment by Thiago-Heleno** [comment]
I managed to make it work by deleting the proxy argument on chromium

**Comment by Deathspike** [comment]
Just to add some background information on this:

AnimeSync contains a proxy core that's responsible for the `proxyServer` setting. Everything pipes through this. That includes *Chromium* and *ffmpeg*, but the URLs for images are also rewritten and redirected through the core. The two external tools, Chromium & ffmpeg, point their proxy setting at that said to make sure they use the `proxyServer` setting.

Removing the arguments to use the proxy core in Chrome or ffmpeg effectively means the `proxyServer` setting is no longer respected. I don't recommend this. The ERR_TUNNEL_CONNECTION_FAILED happens when Chrome can't connect to animesync's proxy core, so I imagine the port on which it connects is not properly bound on your Heroku setup.

You might want to look into that instead.
