### ISSUE TITLE
[FEATURE REQUEST] Add support to VRV.co

### ISSUE THREAD

**Issue by Oujiii** [animeloyalty/animesync#33]
Title speaks for itself. If you are looking to support addtional streaming websites, [VRV](https://vrv.co/) is a good one. They have both Crunchyroll's and HIDIVE's catalog. I know they work with youtube-dl.

**Comment by Deathspike** [comment]
This one might be interesting. Either VRV or HIDIVE directly.
I'm not sure what would be better. Does HIDIVE add anime content not found on Funi/CR?
In a utopia, I'd support only one site with everything on it, haha.

**Comment by Oujiii** [comment]
I'm gonna expand a little bit on this. We have three main streaming services in US, CA, MEX and BRA which are Crunchyroll, Funimation and Hidive. VRV is a platform that has both Crunchyroll and Hidive catalog, when you have a VRV subscription (the full one), you have access to all their content, but there is a catch, VRV is only available in the US. To bypass that, you can link your VRV account to a Crunchyroll account and enjoy premium there, but you can't do the same for Hidive, so if you are a VRV subscriber (which I am), you can only watch Hidive content on VRV.
Hidive does have content not found on those two, like Made in Abyss, Redo of Healer (which I totally did not watch) and Corpse Party, to name a few.

**Comment by Deathspike** [comment]
It took me a little while to get to this request, but I've just added experimental support in `1.1.0-beta.0`. So far, I've only tested with the *Crunchyroll* channel on *vrv* since it has free episodes, so I'm unsure whether *Hidive* content will work without further modifications. I doubt that it works, but could you give it a try on a *Hidive* series?

Install with `npm -g install animesync@beta`.
Download with `animesync download https://vrv.co/series/GY1QK2N1R/Redo-of-Healer`.

If it fails, please attach your logs here or send them to me by e-mail (meister.deathspike@outlook.com).
I'll set up an account with trial subscription in the next few days to test it further on my end.

To be continued :-)

**Comment by Deathspike** [comment]
I'm continuing this one in #42

**Comment by heptahex** [comment]
HiDIVE offers Home Video editions where Crunchyroll and Funimation do not offer. For example, those who enjoy ecchi animes, HiDIVE would be a great site. Due to their Home Videos I won't need to buy a BDMV. The whole season of To Love Ru is uncensored on HiDIVE.
