### ISSUE TITLE
[FEATURE REQUEST] Add ability to save as mp4 and subtitles

### ISSUE THREAD

**Issue by Differentunic** [animeloyalty/animesync#40]
Instead of packaging the videos as .mkv, leave as .mp4 for videos and .vtt for subtitles.

**Comment by Deathspike** [comment]
I have to ask; why do you want this feature?
Is there a good reason you don't want MKVs as output?

**Comment by Differentunic** [comment]
> I have to ask; why do you want this feature?
> Is there a good reason you don't want MKVs as output?

To play in a web browser. plyr does not support .mkv and requires .vtt subtitles.

**Comment by Deathspike** [comment]
I assume that this is programmatic use. In this case, you can use the `animesync` API.
Run `animesync server` and open http://localhost:6583/api/ in your browser.
You'll see that the `/api/remote/stream` route yields `sources` and `subtitles`.

Funimation yields `.vtt` subtitles, but Crunchyroll yields `.ass` subtitles.
You'll need a `.ass` renderer in your web project. I recommend `subtitles-octopus`.
Conversion between `.ass` and `.vtt` will lose information, so it's not recommended.
See https://github.com/animeloyalty/animeloyalty-client for an example.

If this is not for programmatic use, please elaborate further on your use case.
Just for context; I don't intend to add features unless there's a *really* good reason for it.
That's because every feature comes with a maintenance cost, and design implications.

Let me know if this helps :-)

**Comment by Differentunic** [comment]
Thanks for the help!
Would you be able to elaborate on how to use the stream API?

**Comment by Deathspike** [comment]
Sure. Use the series URL, without language tags, in `/api/remote/series`. Example:
https://www.crunchyroll.com/dont-toy-with-me-miss-nagatoro

![image](https://user-images.githubusercontent.com/198601/126058964-ab3b51d5-7ca9-4e64-875f-92df1cebe885.png)

Then you'll have the episode URLs. You can continue with `/api/remote/stream` on the episode URL. Example:
https://www.crunchyroll.com/dont-toy-with-me-miss-nagatoro/episode-1-senpai-is-a-bit-senpai-dont-you-ever-get-angry-811065

![image](https://user-images.githubusercontent.com/198601/126059053-71b44b90-743b-43e5-91e3-a321e7b12ff6.png)

You can see that this result has `sources` and `subtitles`. Right now, a `source` is always `hls`.
That can be plugged into `ffmpeg`. I'll abbreviate the URL, but as an example:

    ffmpeg -i "http://localhost:6583/api/rewrite/master/https%3A%2F%2Fpl.crunchyroll.com%2Fevs1%2Fff06ec45dfd154b9c61950e39af5b6cd" "output.mp4"

This'll dump the video file as a `.mp4`. You can look at `Sync.ts` to see how `animesync` does it for `.mkv`.
See https://github.com/animeloyalty/animesync/blob/master/src/cli/classes/Sync.ts. 

Of course, if you're using a web player, you can stream it directly as well. Example:
https://github.com/animeloyalty/animeloyalty-client/blob/master/src/session/views/MainView.tsx
In `animeloyalty-client`, this source URL is just fed into `hls.js` to load the video stream into a `<video />` HTML tag.

Your last piece of the puzzle is your subtitles. They're all in the `subtitles` key.
Just download them with a regular HTTP call and save them as you see fit.

I hope this helps!

**Comment by RaulRohjans** [comment]
I posted a thread requesting something similar once, and since then I made a script in python that downloads the mp4 and subtitles separately. 

If you are familiar with the language or want to take a look I can share it. I made mine to suit my needs so you would probably have to modify it a bit, but the principle is the same.

**Comment by Deathspike** [comment]
Feel free to re-open this issue if you require further assistance with this.
Closing it for now.
