### ISSUE TITLE
Can't bypass regional lock on the API with a VPN

### ISSUE THREAD

**Issue by RaulRohjans** [animeloyalty/animesync#41]
Hello, Im using the API to get information of the titles. Some animes are not available in my country and to bypass this I usually use a VPN (which works fine). However, I noticed that the VPN does not affect the API in any way and when I try to get an episode list, for example, for a locked title it still shows no episodes.

![imagem](https://user-images.githubusercontent.com/77687494/126072494-47e7d252-c63e-4d66-adae-39bea2d72ac2.png)

**Comment by Deathspike** [comment]
I've encountered something similar before. but I'm not sure if your situation has the same root cause. Crunchyroll leaves some regional information in your local storage, which allows reidentification of a region after jumping around with a VPN. The solution in that case was to make sure that local storage is pruned; exit `animesync`, delete the `chrome-data` folder from your *user\animesync* folder, and restart `animesync`. That should solve the issue if this has the same cause.

FWIW the `proxyServer` setting is a more lightweight solution than a full blown VPN, and should work perfectly fine as well. Internally, when you set a different `proxyServer`, it also makes sure that the `chrome-data` folder is deleted. It might be a nice option to use :-)

**Comment by RaulRohjans** [comment]
I will try that out and give feedback.

The reason I didnt use the proxyServer function is because I have a VPN subscription, but the only way to use their servers is by using the app.

**Comment by RaulRohjans** [comment]
While testing, I encountered another problem, I think this is unrelated though. It is giving me invalid credentials.

When using the API:
![imagem](https://user-images.githubusercontent.com/77687494/126079225-f87392c7-53e0-4f9f-a1d6-93bee28aafcb.png)

When trying to download something:
![imagem](https://user-images.githubusercontent.com/77687494/126079242-c63ae3df-725b-46a7-b407-6e2f66a082c2.png)

**Comment by Deathspike** [comment]
Looks like you're using USA-based VPN. They've started forcing people to use the half-finished beta pages when they sign in from the USA (hint: your region is working!).

Right now I recommend not logging in when connecting from the USA.
Once they've fixed their pages to be usable and rolled out to everyone, support for the new CR pages will come.

**Comment by RaulRohjans** [comment]
Okay, so the issue is fixed. Thank you!

**Comment by Deathspike** [comment]
Wanted to let you know that `beta.crunchyroll.com` is now supported.
Give it a go 👍
